<HTML>
<p>Beatriz Cristina Da Silva 05</b>
<p>/HTML>Olá,sou Beatriz Cristina,esse é o meu site,no qual irei desenvolver todas as minhas descobertas com o Github,me aprimorar cada dia
mais,além de sempre estar trazendo novidades atualizadas.</P>
Index.html
